### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by maximAtanasov**
This PR adds Travis CI as a replacement for Circle CI (#176). There is however still one failing test in Traivs.
The log can be seen here: https://travis-ci.org/maximAtanasov/coderadar/jobs/485949802
I've tried different JDK versions (including 201 used in Travis) and different OSes,  but nothing helpled. I've tried running the same commmands in Circle CI and they worked fine. (I noticed our current build only does `gradle zip` and doesn't run tests, I don't know why).

### CODE REVIEW

**Comment by matthiasbalke** [comment]
I'm curious, why do you switch from circle ci to travis?

**Comment by maximAtanasov** [comment]
I've done this because of the open issue. Personally it doesn't matter to me which one we choose as long as we aren't on Circle CI 1.0 (arguably Circle 2.0 is better as it isn't stuck on an old version of Ubuntu), but I don't think it matters all that much which service we use, both do the same things.

**Comment by maximAtanasov** [comment]
Ok, I have reproduced the failing tests in a Linux VM and it seems that they only fail when the tests are run all at once. I have a `@DirtiesContext` annotation to the `TestTemplate` and the Travis build now passes. Someone with access just has to add this repo to Travis.
The build can be seen here:
https://travis-ci.org/maximAtanasov/coderadar/builds/486912328

**Comment by thombergs** [comment]
@matthiasbalke we're moving to travis mainly because I'm more familiar with it and have never understood circle's UI :)

**Pull request merged**
