### PR TITLE
Integrated the CoderadarVisualization UI

### LINKED ISSUE #192: Integrate the CoderadarVisualization UI
As a user, I want to combine selected metrics into a single view in order to gain insights into the code base.

For this, we should include Philippe's [CoderadarVisualization](https://github.com/pschild/CodeRadarVisualization) UI into coderadar itself.

### PR DESCRIPTION
**Pull request by maximAtanasov**
I have integrated the 3D visualization from https://github.com/pschild/CodeRadarVisualization into coderadar-app by merging the two codebases and using material design instead of bootstrap.

Closes #192.

### CODE REVIEW

**Comment by jo2** [comment]
- use color code adesso-blue (#016EC7)?
- change accent color from pink to maybe #f38f56?
- only show 3D-Map button when all comments are analysed

**Comment by maximAtanasov** [comment]
@jo2 
I have adjusted the theme and the button as well as the commits sorting and formatting in the 3D view.

**Comment by maximAtanasov** [comment]
I have removed the button that led to the 3D view.
The user now has to select two commits by clicking on the cards. 
Once two cards are selected, a button pops up and the user can switch to the 3D comparison of the commits.

**Comment by jo2** [comment]
On smaller screens (< width 1510px) some actions in the menu bar are partly or completly hidden (see image)
image
For some combinations (for example AnnotationLocationCheck and AnnotationUseStyleCheck) in the right part there are no metrics is it possible to disable them in the view? maybe with a message 'no metrics available'? If one option is chosen is it maybe even possible to not display all second options which won't result in any metrics?

**Comment by maximAtanasov** [comment]
@jo2 
I have adjusted the control panel to display properly on smaller (but no too small) screens.
As for the metrics, I'm not sure I understand the question, if there are no metrics, they simply aren't displayed in the visualization.

> If one option is chosen is it maybe even possible to not display all second options which won't result in any metrics?

How do I know which combinations won't result in metrics?

**Pull request merged**
